<a href="https://colab.research.google.com/github/Quyen-N/100-days-ML/blob/main/Day_1_Simple_NN_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a sample notebook to test a Neural Network using Tensorflow

#Import

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [ ]:
print(tf.__version__)

2.8.0


#Generate train & test data
In this part I will make a simple train dataset defined by formula: 

Y =  X * W + noise

In [ ]:
W = np.array([[6],[8],[3]], dtype=np.int32)
print(W)

[[6]
 [8]
 [3]]


In [ ]:
def generate_data():
  x = np.random.randint(10000, size=(1,2))
  y = np.matmul(np.c_[[[1]], x], W) + np.random.uniform(-1,1,size=(1,1))
  yield x, y

In [ ]:
next(generate_data())

(array([[8169,  262]]), array([[66144.59689404]]))

In [ ]:
dataset = tf.data.Dataset.from_generator(generate_data, output_signature=(
    tf.TensorSpec(shape=(1,2)), tf.TensorSpec(shape=(1,1))))
dataset = dataset.repeat().batch(32).prefetch(1)

In [ ]:
def calculate_output(x):
   return np.matmul(np.c_[[[1]], x], W)

In [ ]:
for x, y in dataset.take(1):
  print(x[0], y[0])
  print(calculate_output(x[0]))

tf.Tensor([[7419.  407.]], shape=(1, 2), dtype=float32) tf.Tensor([[60578.688]], shape=(1, 1), dtype=float32)
[[60579.]]


#Build model & train
Now we will build a simple peceptron then train it and compare trained weights with our original W matrix

In [ ]:
keras.backend.clear_session()

In [ ]:
model = keras.models.Sequential([
  keras.layers.Input(shape=(1,2)),
  keras.layers.Dense(1)
])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1, 1)              3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
optimizer = keras.optimizers.Nadam()
model.compile(loss='mse', optimizer=optimizer)
history = model.fit(dataset, epochs=100, steps_per_epoch=200)

Epoch 1/100
200/200 [==============================] - 7s 35ms/step - loss: 14339826.0000
Epoch 2/100
200/200 [==============================] - 7s 35ms/step - loss: 9613259.0000
Epoch 3/100
200/200 [==============================] - 7s 34ms/step - loss: 6373729.5000
Epoch 4/100
200/200 [==============================] - 7s 35ms/step - loss: 4124158.0000
Epoch 5/100
200/200 [==============================] - 7s 35ms/step - loss: 2498681.7500
Epoch 6/100
200/200 [==============================] - 7s 35ms/step - loss: 1349600.6250
Epoch 7/100
200/200 [==============================] - 7s 35ms/step - loss: 690045.9375
Epoch 8/100
200/200 [==============================] - 7s 34ms/step - loss: 346085.7500
Epoch 9/100
200/200 [==============================] - 7s 35ms/step - loss: 149078.5938
Epoch 10/100
200/200 [==============================] - 7s 35ms/step - loss: 58932.1836
Epoch 11/100
200/200 [==============================] - 7s 36ms/step - loss: 20994.1328
Epoch 12/100
200/200 [===

KeyboardInterrupt: ignored

In [ ]:
model.layers[0].weights

[<tf.Variable 'dense/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[7.99994  ],
        [2.9999318]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([6.701979], dtype=float32)>]

In [ ]:
print(W)

[[6]
 [8]
 [3]]


OK. Our model has learned the weights that we desired. Because of noise it cannot do better than that. 

So we have built a simple linear model and trained it successfully. We will findout more interesting thing about modeling and handle more complex problem in the next notebook.